### PR TITLE
Misc/phys x export

### PR DESCRIPTION
**Pull request by jerome-jacob**
Support for Maya PhysX plugin export
https://github.com/fl4re/OpenCOLLADA/issues/4

### CODE REVIEW

**Comment by mbarnes-sb** [comment]
Please create an issue (in this repo) for tracking this PR.

**Comment by mbarnes-sb** [comment]
Also @jerome-jacob I think this PR needs to be targeted at the parent repo. I think we don't want to merge PR into our local master branch, but rather the upstream repo. @RemiArnaud you agree right?

Assuming I'm right then we will close this PR without merging and create a new one as described.

**Comment by shane-calnan-sb** [comment]
Issue logged here: https://github.com/fl4re/OpenCOLLADA/issues/4

**Comment by RemiArnaud** [comment]
opencollada PRs needs to be opened in https://github.com/khronosgroup/opencollada

In fact, we do not want to have any divergences between this (fl4re) clone and the official opencollada repository. So we will not want to merge anything in this clone master.

Also, Jenkins PR build is set-up to work on the official opencollada. We can't run it there.

therefore, I'm closing this PR.

**Comment by RemiArnaud** [comment]
left comment and closed PR

**Comment by mbarnes-sb** [comment]
We can create PR in either direction:
1. From Khronos repo to Fl4re repo
2. From Fl4re repo to Khronos repo

At this time, I don't think it matters which direction we choose or which repo owns the PR (since they are public repos). What matters is tracking Starbreeze contributions in this repo from now on: feature branches and issues.

In future, I plan to change from dropbox to using github release services - https://help.github.com/articles/about-releases/ . The metadata (issues, tags, etc) for each release will need to be available in this repo.

**Pull request closed without merging**
